config/routes.rb
Rails.application.routes.draw do

  resources :customs_agents
  resources :companies
  resources :products
  resources :legal_representatives

  get 'index/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get '/', to: 'index#index'
  root 'index#index'

  get '/faq', to: 'index#faq', as: 'faq'

  get '/register/company', to: 'companies#new', as: 'register_company'
  get '/register/legal_representative', to: 'legal_representatives#new', as: 'register_legal_representative'
  get '/register/product', to: 'products#new', as: 'register_product'

  get '/register/product/success', to: 'products#success', as: 'product_success'

end

app/models/company.rb
class Company< ActiveRecord::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to register_product_path, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :RFC, :billing_address, :shipping_address)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :RFC %><br>
    <%= f.text_field :RFC %>
  </div>
  <div class="field">
    <%= f.label :billing_address %><br>
    <%= f.text_field :billing_address %>
  </div>
  <div class="field">
    <%= f.label :shipping_address %><br>
    <%= f.text_field :shipping_address %>
  </div>
  <div class="actions">
    <%= f.submit "Continue" %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rfc</th>
      <th>Billing address</th>
      <th>Shipping address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.RFC %></td>
        <td><%= company.billing_address %></td>
        <td><%= company.shipping_address %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<section class="registrations-view">
  <h1>Register Your Company</h1><div class="logout_button_register"><%= button_to (t 'views.devise.logout'), destroy_user_session_path, :method => :delete %></div>
  <%= render 'form' %>
</section>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Rfc:</strong>
  <%= @company.RFC %>
</p>

<p>
  <strong>Billing address:</strong>
  <%= @company.billing_address %>
</p>

<p>
  <strong>Shipping address:</strong>
  <%= @company.shipping_address %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>