config/routes.rb
Rails.application.routes.draw do

  resources :customs_agents
  resources :companies
  resources :products
  resources :legal_representatives

  get 'index/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get '/', to: 'index#index'
  root 'index#index'

  get '/faq', to: 'index#faq', as: 'faq'

  get '/register/company', to: 'companies#new', as: 'register_company'
  get '/register/legal_representative', to: 'legal_representatives#new', as: 'register_legal_representative'
  get '/register/product', to: 'products#new', as: 'register_product'

  get '/register/product/success', to: 'products#success', as: 'product_success'

end

app/models/customs_agent.rb
class CustomsAgent < ActiveRecord::Base
end

app/controllers/customs_agents_controller.rb
class CustomsAgentsController < ApplicationController
  before_action :set_customs_agent, only: [:show, :edit, :update, :destroy]

  # GET /customs_agents
  # GET /customs_agents.json
  def index
    @customs_agents = CustomsAgent.all
  end

  # GET /customs_agents/1
  # GET /customs_agents/1.json
  def show
  end

  # GET /customs_agents/new
  def new
    @customs_agent = CustomsAgent.new
  end

  # GET /customs_agents/1/edit
  def edit
  end

  # POST /customs_agents
  # POST /customs_agents.json
  def create
    @customs_agent = CustomsAgent.new(customs_agent_params)

    respond_to do |format|
      if @customs_agent.save
        format.html { redirect_to @customs_agent, notice: 'Customs agent was successfully created.' }
        format.json { render :show, status: :created, location: @customs_agent }
      else
        format.html { render :new }
        format.json { render json: @customs_agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customs_agents/1
  # PATCH/PUT /customs_agents/1.json
  def update
    respond_to do |format|
      if @customs_agent.update(customs_agent_params)
        format.html { redirect_to @customs_agent, notice: 'Customs agent was successfully updated.' }
        format.json { render :show, status: :ok, location: @customs_agent }
      else
        format.html { render :edit }
        format.json { render json: @customs_agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customs_agents/1
  # DELETE /customs_agents/1.json
  def destroy
    @customs_agent.destroy
    respond_to do |format|
      format.html { redirect_to customs_agents_url, notice: 'Customs agent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customs_agent
      @customs_agent = CustomsAgent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customs_agent_params
      params.require(:customs_agent).permit(:name, :last_name, :key, :email, :phone)
    end
end

app/helpers/customs_agents_helper.rb
module CustomsAgentsHelper
end

app/views/customs_agents/_form.html.erb
<%= form_for(@customs_agent) do |f| %>
  <% if @customs_agent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customs_agent.errors.count, "error") %> prohibited this customs_agent from being saved:</h2>

      <ul>
      <% @customs_agent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :key %><br>
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customs_agents/edit.html.erb
<h1>Editing Customs Agent</h1>

<%= render 'form' %>

<%= link_to 'Show', @customs_agent %> |
<%= link_to 'Back', customs_agents_path %>

app/views/customs_agents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Customs Agents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Last name</th>
      <th>Key</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customs_agents.each do |customs_agent| %>
      <tr>
        <td><%= customs_agent.name %></td>
        <td><%= customs_agent.last_name %></td>
        <td><%= customs_agent.key %></td>
        <td><%= customs_agent.email %></td>
        <td><%= customs_agent.phone %></td>
        <td><%= link_to 'Show', customs_agent %></td>
        <td><%= link_to 'Edit', edit_customs_agent_path(customs_agent) %></td>
        <td><%= link_to 'Destroy', customs_agent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customs agent', new_customs_agent_path %>

app/views/customs_agents/new.html.erb
<h1>New Customs Agent</h1>

<%= render 'form' %>

<%= link_to 'Back', customs_agents_path %>

app/views/customs_agents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customs_agent.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @customs_agent.last_name %>
</p>

<p>
  <strong>Key:</strong>
  <%= @customs_agent.key %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customs_agent.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @customs_agent.phone %>
</p>

<%= link_to 'Edit', edit_customs_agent_path(@customs_agent) %> |
<%= link_to 'Back', customs_agents_path %>