config/routes.rb
Rails.application.routes.draw do

  resources :customs_agents
  resources :companies
  resources :products
  resources :legal_representatives

  get 'index/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get '/', to: 'index#index'
  root 'index#index'

  get '/faq', to: 'index#faq', as: 'faq'

  get '/register/company', to: 'companies#new', as: 'register_company'
  get '/register/legal_representative', to: 'legal_representatives#new', as: 'register_legal_representative'
  get '/register/product', to: 'products#new', as: 'register_product'

  get '/register/product/success', to: 'products#success', as: 'product_success'

end

app/models/legal_representative.rb
class LegalRepresentative < ActiveRecord::Base
  belongs_to :company
end

app/controllers/legal_representatives_controller.rb
class LegalRepresentativesController < ApplicationController
  before_action :set_legal_representative, only: [:show, :edit, :update, :destroy]

  # GET /legal_representatives
  # GET /legal_representatives.json
  def index
    @legal_representatives = LegalRepresentative.all
  end

  # GET /legal_representatives/1
  # GET /legal_representatives/1.json
  def show
  end

  # GET /legal_representatives/new
  def new
    @legal_representative = LegalRepresentative.new
  end

  # GET /legal_representatives/1/edit
  def edit
  end

  # POST /legal_representatives
  # POST /legal_representatives.json
  def create
    @legal_representative = LegalRepresentative.new(legal_representative_params)

    respond_to do |format|
      if @legal_representative.save
        format.html { redirect_to register_product_path, notice: 'Legal representative was successfully created.' }
        format.json { render :show, status: :created, location: @legal_representative }
      else
        format.html { render :new }
        format.json { render json: @legal_representative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /legal_representatives/1
  # PATCH/PUT /legal_representatives/1.json
  def update
    respond_to do |format|
      if @legal_representative.update(legal_representative_params)
        format.html { redirect_to @legal_representative, notice: 'Legal representative was successfully updated.' }
        format.json { render :show, status: :ok, location: @legal_representative }
      else
        format.html { render :edit }
        format.json { render json: @legal_representative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /legal_representatives/1
  # DELETE /legal_representatives/1.json
  def destroy
    @legal_representative.destroy
    respond_to do |format|
      format.html { redirect_to legal_representatives_url, notice: 'Legal representative was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_legal_representative
      @legal_representative = LegalRepresentative.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def legal_representative_params
      params.require(:legal_representative).permit(:name, :last_name, :phone, :email, :company_id)
    end
end

app/helpers/legal_representatives_helper.rb
module LegalRepresentativesHelper
end

app/views/legal_representatives/_form.html.erb
<%= form_for(@legal_representative) do |f| %>
  <% if @legal_representative.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@legal_representative.errors.count, "error") %> prohibited this legal_representative from being saved:</h2>

      <ul>
      <% @legal_representative.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br>
    <%= f.text_field :company_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/legal_representatives/edit.html.erb
<h1>Editing Legal Representative</h1>

<%= render 'form' %>

<%= link_to 'Show', @legal_representative %> |
<%= link_to 'Back', legal_representatives_path %>

app/views/legal_representatives/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Legal Representatives</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Last name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @legal_representatives.each do |legal_representative| %>
      <tr>
        <td><%= legal_representative.name %></td>
        <td><%= legal_representative.last_name %></td>
        <td><%= legal_representative.phone %></td>
        <td><%= legal_representative.email %></td>
        <td><%= legal_representative.company %></td>
        <td><%= link_to 'Show', legal_representative %></td>
        <td><%= link_to 'Edit', edit_legal_representative_path(legal_representative) %></td>
        <td><%= link_to 'Destroy', legal_representative, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Legal representative', new_legal_representative_path %>

app/views/legal_representatives/new.html.erb
<section class="registrations-view">
  <h1>Enter The Company's Legal Representative Info</h1><div class="logout_button_register"><%= button_to (t 'views.devise.logout'), destroy_user_session_path, :method => :delete %></div>
  <%= render 'form' %>
</section>

app/views/legal_representatives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @legal_representative.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @legal_representative.last_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @legal_representative.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @legal_representative.email %>
</p>

<p>
  <strong>Company:</strong>
  <%= @legal_representative.company %>
</p>

<%= link_to 'Edit', edit_legal_representative_path(@legal_representative) %> |
<%= link_to 'Back', legal_representatives_path %>